/* CREATE AND LOAD ETRACT TABLE (EXT) */
DROP TABLE IF EXISTS EXT_IMDB_BASE_TITLE_CREW;

	/* TABLE NAME AND COLUMNS SHOULD MATCH SOURCE */
	CREATE TABLE EXT_IMDB_BASE_TITLE_CREW (
		TCONST TEXT
		,DIRECTORS TEXT
		,WRITERS TEXT
		);

/* CHARACTER CASE OF THE FOLLOWING LOAD SEQUENCE MUST REMAIN */
\COPY EXT_IMDB_BASE_TITLE_CREW FROM PROGRAM 'curl "https://datasets.imdbws.com/title.crew.tsv.gz" | gunzip' QUOTE '|' DELIMITER E '\t' NULL '\N' CSV HEADER;

ANALYZE EXT_IMDB_BASE_TITLE_CREW;

COMMIT;
