/* CREATE AND LOAD ETRACT TABLE (EXT) */
DROP TABLE IF EXISTS EXT_IMDB_BASE_TITLE_AKAS;

/* TABLE NAME AND COLUMNS SHOULD MATCH SOURCE */
CREATE TABLE EXT_IMDB_BASE_TITLE_AKAS (
	    TITLEID TEXT,
	    ORDERING INT,
	    TITLE TEXT,
	    REGION TEXT,
	    LANGUAGE TEXT,
	    TYPES TEXT,
	    ATTRIBUTES TEXT,
	    ISORIGINALTITLE INT
	);

/* CASE OF FOLLOWING LOAD SEQUENCE MUST REMAIN */
\COPY EXT_IMDB_BASE_TITLE_AKAS FROM PROGRAM 'curl "https://datasets.imdbws.com/title.akas.tsv.gz" | gunzip' QUOTE '|' DELIMITER E'\t' NULL '\N' CSV HEADER;

ANALYZE EXT_IMDB_BASE_TITLE_AKAS;

COMMIT;
