/* DROP EXISTING DATA WAREHOUSE TABLE	(DW) */
DROP TABLE IF EXISTS DW_IMDB_BASE_TITLE_PRINCIPALS;

/* CREATE DW TABLE */
CREATE TABLE DW_IMDB_BASE_TITLE_PRINCIPALS (
	P_TCONST_ID INTEGER NULL
	,TCONST_NK TEXT NOT NULL-- ALPHANUMERIC IDENTIFIER OF PRINCIPALS
	,ORDERING TEXT NOT NULL -- ALPHANUMERIC IDENTIFIER OF THE PARENT TV SERIES
	,SEASONNUMBER INT NOT NULL -- SEASON NUMBER THE PRINCIPALS BELONGS TO
	,PRINCIPALSNUMBER INT NOT NULL -- PRINCIPALS NUMBER OF THE TCONST IN THE TV SERIES
	,SRC_ID TEXT NOT NULL
	,LOAD_DATE DATE NOT NULL
	,LAST_UPDATE DATE NOT NULL
	,NOTE TEXT NOT NULL
  ,CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,PRIMARY KEY (P_TCONST_ID)
	);

	CREATE INDEX DW_IMDB_BASE_TITLE_PRINCIPALS_INDX ON DW_IMDB_BASE_TITLE_PRINCIPALS (TCONST_NK);

  CREATE TRIGGER DW_IMDB_BASE_TITLE_PRINCIPALS_UPDT
  BEFORE UPDATE ON DW_IMDB_BASE_TITLE_PRINCIPALS
  FOR EACH ROW
  EXECUTE PROCEDURE TRIGGER_SET_TIMESTAMP();

/* INSERT DEFAULT VALUES */
INSERT INTO DW_IMDB_BASE_TITLE_PRINCIPALS(
	P_TCONST_ID
	,TCONST_NK
	,ORDERING
	,SEASONNUMBER
	,PRINCIPALSNUMBER
	,SRC_ID
	,LOAD_DATE
	,LAST_UPDATE
	,NOTE
	)
VALUES (
	0 /* AS P_TCONST_ID */
	,'N/A' /* AS TCONST_NK*/
	,'N/A' /* AS ORDERING */
	,0 /* AS SEASONNUMBER */
	,0 /* AS PRINCIPALSNUMBER */
	,'TITLE_PRINCIPALS' /* AS SRC_ID */
	,'19000101' /* AS LOAD_DATE */
	,'19000101' /* AS LAST_UPDATE */
	,'N/A' /* AS NOTE */
	);

	COMMIT;
