/* CREATE STAGING VIEW (SV) */
DROP VIEW IF EXISTS SV_IMDB_BASE_TITLE_PRINCIPALS;

/* TRANSFORMATION OF EXTERNAL COLUMN NAMES AND REMOVAL OF NULL VALUES */
CREATE VIEW SV_IMDB_BASE_TITLE_PRINCIPALS
AS
SELECT COALESCE(TCONST, 'N/A') AS TCONST_NK
	,COALESCE(ORDERING, 0) AS ORDERING
	,COALESCE(NCONST, 'N/A') AS NCONST
	,COALESCE(CATEGORY, 'N/A') AS CATEGORY
	,COALESCE(JOB, 'N/A') AS JOB
	,COALESCE(CHARACTERS, 'N/A') AS CHARACTERS
	,'TITLE_PRINCIPALS' AS SRC_NAME
	,CURRENT_DATE AS LOAD_DATE
	,'' AS NOTE
FROM EXT_IMDB_BASE_TITLE_PRINCIPALS;
