TRUNCATE TABLE X_IMDB_BASE_TITLE_BASICS_CHG;

/* DETECT CHANGES */
INSERT INTO X_IMDB_BASE_TITLE_BASICS_CHG (
	TCONST_ID
	,TCONST_NK
	,TITLETYPE_NK
	,PRIMARYTITLE_DESC
	,ORIGINALTITLE_DESC
	,ISADULT
	,STARTYEAR
	,ENDYEAR
	,RUNTIMEMINUTES
	,GENRES
	,SRC_ID
	,LOAD_DATE
	,NOTE
	,CHG_FLG
	)
SELECT T.TCONST_ID
	,S.TITLETYPE_NK
	,S.PRIMARYTITLE_DESC
	,S.ORIGINALTITLE_DESC
	,S.ISADULT
	,S.STARTYEAR
	,S.ENDYEAR
	,S.RUNTIMEMINUTES
	,S.GENRES
	,S.SRC_ID
	,S.LOAD_DATE
	,S.NOTE
	,CASE
		WHEN T.TCONST_ID IS NULL
			THEN 'I'
		ELSE 'X'
		END
FROM ST_IMDB_BASE_TITLE_BASICS S
LEFT OUTER JOIN DW_IMDB_BASE_TITLE_BASICS T
	ON T.TCONST_NK = S.TCONST_NK
WHERE T.TCONST_ID IS NULL
	OR T.PRIMARYTITLE_DESC <> S.PRIMARYTITLE_DESC
	OR T.ORIGINALTITLE_DESC <> S.ORIGINALTITLE_DESC
	OR T.ISADULT <> S.ISADULT
	OR T.STARTYEAR <> S.STARTYEAR
	OR T.ENDYEAR <> S.ENDYEAR
	OR T.RUNTIMEMINUTES <> S.RUNTIMEMINUTES
	OR T.GENRES <> S.GENRES
	OR T.SRC_ID <> S.SRC_ID
	OR T.NOTE <> S.NOTE;

ANALYZE X_IMDB_BASE_TITLE_BASICS_CHG;

/* INSERT CHANGES */
INSERT INTO DW_IMDB_BASE_TITLE_BASICS (
	TCONST_ID
	,TCONST_NK
	,TITLETYPE_NK
	,PRIMARYTITLE_DESC
	,ORIGINALTITLE_DESC
	,ISADULT
	,STARTYEAR
	,ENDYEAR
	,RUNTIMEMINUTES
	,GENRES
	,SRC_ID
	,LOAD_DATE
	,LAST_UPDATE
	,NOTE
	)
SELECT M.MAX_ID + ROW_NUMBER() OVER (
		ORDER BY S.TCONST_NK
		)
	,S.TCONST_NK
	,S.TITLETYPE_NK
	,S.PRIMARYTITLE_DESC
	,S.ORIGINALTITLE_DESC
	,S.ISADULT
	,S.STARTYEAR
	,S.ENDYEAR
	,S.RUNTIMEMINUTES
	,S.GENRES
	,S.SRC_ID
	,S.LOAD_DATE
	,S.LOAD_DATE
	,S.NOTE
FROM X_IMDB_BASE_TITLE_BASICS_CHG S
	,(
		SELECT MAX(TCONST_ID) MAX_ID
		FROM DW_IMDB_BASE_TITLE_BASICS
		) M
WHERE S.CHG_FLG = 'I';

/* UPDATE CHANGES */
UPDATE DW_IMDB_BASE_TITLE_BASICS
SET TCONST_NK = S.TCONST_NK
	,TITLETYPE_NK = S.TITLETYPE_NK
	,PRIMARYTITLE_DESC = S.PRIMARYTITLE_DESC
	,ORIGINALTITLE_DESC = S.ORIGINALTITLE_DESC
	,ISADULT = S.ISADULT
	,STARTYEAR = S.STARTYEAR
	,ENDYEAR = S.ENDYEAR
	,RUNTIMEMINUTES  = S.RUNTIMEMINUTES
	,GENRES = S.GENRES
	,SRC_ID = S.SRC_ID
	,LAST_UPDATE = S.LOAD_DATE
	,NOTE = S.NOTE
FROM X_IMDB_BASE_TITLE_BASICS_CHG S
WHERE S.TCONST_NK = DW_IMDB_BASE_TITLE_BASICS.TCONST_NK
	AND S.CHG_FLG = 'X';

ANALYZE DW_IMDB_BASE_TITLE_BASICS;

/* SAVE LOAD LOG HISTORY */
INSERT INTO X_IMDB_BASE_LOG (
	LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT
	)
SELECT NOW()
	,30
	,S.SRC_ID
	,'DW_IMDB_BASE_TITLE_BASICS'
	,S.LOAD_DATE AS LOAD_DATE
	,T.ST_ROW_COUNT AS ST_ROW_COUNT
	,COUNT(S.*) AS DW_ROW_COUNT
	,NULL AS DISTINCT_COUNT
FROM DW_IMDB_BASE_TITLE_BASICS S
JOIN X_IMDB_BASE_LOG T
	ON S.SRC_ID = T.SRC_ID
    AND S.LOAD_DATE = T.LOAD_DATE
WHERE T.LOAD_SEQ_NUM = 10
	AND T.OBJECT_NAME = 'ST_IMDB_BASE_TITLE_BASICS'
	AND T.LOAD_DATE = (
		SELECT MAX(LOAD_DATE)
		FROM ST_IMDB_BASE_TITLE_BASICS
		)
GROUP BY S.SRC_ID
	,S.LOAD_DATE
	,T.ST_ROW_COUNT;

/* SAVE ETL LOG HISTORY */
INSERT INTO ETL_LOG (
	SUBJECT_AREA
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT
	,FAIL_CHECK_BOOL_1
	,ERROR_MESSAGE_1
	,FAIL_CHECK_BOOL_2
	,ERROR_MESSAGE_2
	,FAIL_CHECK_BOOL_3
	,ERROR_MESSAGE_3
	)
SELECT 'IMDB_BASE'
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT
	,CASE
		WHEN SUM(ST_ROW_COUNT) = SUM(DW_ROW_COUNT)
			THEN 0
		ELSE 1
		END
	,CONCAT (
		'ROW COUNTS FOR THE LATEST LATEST TRANSACTION DATE DO NOT MATCH SOURCE. SOURCE ST (ST_IMDB_BASE_TITLE_BASICS) = '
		,ST_ROW_COUNT
		,' DW (DW_IMDB_BASE_TITLE_BASICS) = '
		,DW_ROW_COUNT
		,'.'
		)
	,0
	,'N/A'
	,0
	,'N/A'
FROM X_IMDB_BASE_LOG
WHERE LOAD_SEQ_NUM = 30
GROUP BY LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT;

COMMIT;
