TRUNCATE TABLE X_IMDB_BASE_TITLE_BASICS_CHG;

/* DETECT CHANGES */
INSERT INTO X_IMDB_BASE_TITLE_BASICS_CHG (
	P_TCONST_ID
	,TCONST_NK
	,TITLETYPE
	,PRIMARYTITLE
	,ORIGINALTITLE
	,ISADULT
	,STARTYEAR
	,ENDYEAR
	,RUNTIMEMINUTES
	,GENRES
	,SRC_ID
	,LOAD_DATE
	,NOTE
	,CHG_FLG
	)
SELECT T.P_TCONST_ID
	,S.TITLETYPE
	,S.PRIMARYTITLE
	,S.ORIGINALTITLE
	,S.ISADULT
	,S.STARTYEAR
	,S.ENDYEAR
	,S.RUNTIMEMINUTES
	,S.GENRES
	,S.SRC_ID
	,S.LOAD_DATE
	,S.NOTE
	,CASE
		WHEN T.P_TCONST_ID IS NULL
			THEN 'I'
		ELSE 'X'
		END
FROM ST_IMDB_BASE_TITLE_BASICS S
LEFT OUTER JOIN DW_IMDB_BASE_TITLE_BASICS T
	ON T.TCONST_NK = S.TCONST_NK
WHERE T.P_TCONST_ID IS NULL
	OR T.PRIMARYTITLE <> S.PRIMARYTITLE
	OR T.ORIGINALTITLE <> S.ORIGINALTITLE
	OR T.ISADULT <> S.ISADULT
	OR T.STARTYEAR <> S.STARTYEAR
	OR T.ENDYEAR <> S.ENDYEAR
	OR T.RUNTIMEMINUTES <> S.RUNTIMEMINUTES
	OR T.GENRES <> S.GENRES
	OR T.SRC_ID <> S.SRC_ID
	OR T.NOTE <> S.NOTE;

ANALYZE X_IMDB_BASE_TITLE_BASICS_CHG;

/* SAVE CURRENT X_CHG LOAD LOG */
INSERT INTO X_IMDB_BASE_LOG (
	LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT
	)
SELECT NOW()
	,20
	,S.SRC_ID
	,'X_IMDB_BASE_TITLE_BASICS_CHG'
	,MAX(S.LOAD_DATE)
	,SUM(ROW_COUNT)
	,SUM(DISTINCT_PK_COUNT)
FROM (
	SELECT TCONST_NK
		,SRC_ID
		,MAX(LOAD_DATE) AS LOAD_DATE
		,COUNT(*) AS ROW_COUNT
		,1 AS DISTINCT_PK_COUNT
	FROM X_IMDB_BASE_TITLE_BASICS_CHG
	GROUP BY TCONST_NK
		,SRC_ID
	) AS S
GROUP BY S.SRC_ID;

/* SAVE X_CHG ETL LOG HISTORY */
INSERT INTO ETL_LOG (
	SUBJECT_AREA
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT
	,FAIL_CHECK_BOOL_1
	,ERROR_MESSAGE_1
	,FAIL_CHECK_BOOL_2
	,ERROR_MESSAGE_2
	)
SELECT 'IMDB_BASE'
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT
	,CASE
		WHEN COUNT(*) > 0
			THEN 0
		ELSE 1
		END
	,'NO RECORDS TO UPSERT. (TABLE X_IMDB_BASE_TITLE_BASICS_CHG).'
	,CASE
		WHEN SUM(ROW_COUNT) = SUM(DISTINCT_PK_COUNT)
			THEN 0
		ELSE 1
		END
	,'DATA SOURCE FAILED PRIMARY KEY TEST. (TABLE X_IMDB_BASE_TITLE_BASICS_CHG).'
FROM X_IMDB_BASE_LOG
WHERE LOAD_SEQ_NUM = 20
GROUP BY LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT;

/* INSERT CHANGES */
INSERT INTO DW_IMDB_BASE_TITLE_BASICS (
	P_TCONST_ID
	,TCONST_NK
	,TITLETYPE
	,PRIMARYTITLE
	,ORIGINALTITLE
	,ISADULT
	,STARTYEAR
	,ENDYEAR
	,RUNTIMEMINUTES
	,GENRES
	,SRC_ID
	,LOAD_DATE
	,LAST_UPDATE
	,NOTE
	)
SELECT M.MAX_ID + ROW_NUMBER() OVER (
		ORDER BY S.TCONST_NK
		)
	,S.TCONST_NK
	,S.TITLETYPE
	,S.PRIMARYTITLE
	,S.ORIGINALTITLE
	,S.ISADULT
	,S.STARTYEAR
	,S.ENDYEAR
	,S.RUNTIMEMINUTES
	,S.GENRES
	,S.SRC_ID
	,S.LOAD_DATE
	,S.LOAD_DATE
	,S.NOTE
FROM X_IMDB_BASE_TITLE_BASICS_CHG S
	,(
		SELECT MAX(P_TCONST_ID) MAX_ID
		FROM DW_IMDB_BASE_TITLE_BASICS
		) M
WHERE S.CHG_FLG = 'I';

/* UPDATE CHANGES */
UPDATE DW_IMDB_BASE_TITLE_BASICS
SET TCONST_NK = S.TCONST_NK
	,TITLETYPE = S.TITLETYPE
	,PRIMARYTITLE = S.PRIMARYTITLE
	,ORIGINALTITLE = S.ORIGINALTITLE
	,ISADULT = S.ISADULT
	,STARTYEAR = S.STARTYEAR
	,ENDYEAR = S.ENDYEAR
	,RUNTIMEMINUTES  = S.RUNTIMEMINUTES
	,GENRES = S.GENRES
	,SRC_ID = S.SRC_ID
	,LAST_UPDATE = S.LOAD_DATE
	,NOTE = S.NOTE
FROM X_IMDB_BASE_TITLE_BASICS_CHG S
WHERE S.TCONST_NK = DW_IMDB_BASE_TITLE_BASICS.TCONST_NK
	AND S.CHG_FLG = 'X';

ANALYZE DW_IMDB_BASE_TITLE_BASICS;

/* SAVE CURRENT DW LOAD LOG */
INSERT INTO X_IMDB_BASE_LOG (
	LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT
	)
SELECT NOW()
	,30
	,DW.SRC_ID
	,'DW_IMDB_BASE_TITLE_BASICS'
	,MAX(DW.LAST_UPDATE)
	,SUM(ROW_COUNT)
	,SUM(DISTINCT_PK_COUNT)
FROM (
	SELECT DW.TCONST_NK
		,DW.SRC_ID
		,MAX(DW.LAST_UPDATE) AS LAST_UPDATE
		,COUNT(*) AS ROW_COUNT
		,1 AS DISTINCT_PK_COUNT
	FROM DW_IMDB_BASE_TITLE_BASICS DW
	JOIN X_IMDB_BASE_TITLE_BASICS_CHG X
		ON DW.TCONST_NK = X.TCONST_NK
	WHERE DW.LAST_UPDATE = (
			SELECT MAX(LOAD_DATE)
			FROM X_IMDB_BASE_TITLE_BASICS_CHG
			)
	GROUP BY DW.TCONST_NK
		,DW.SRC_ID
	) AS DW
GROUP BY DW.SRC_ID;

/* SAVE ETL LOG HISTORY */
INSERT INTO ETL_LOG (
	SUBJECT_AREA
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT
	,FAIL_CHECK_BOOL_1
	,ERROR_MESSAGE_1
	,FAIL_CHECK_BOOL_2
	,ERROR_MESSAGE_2
	,FAIL_CHECK_BOOL_3
	,ERROR_MESSAGE_3
	)
SELECT 'IMDB_BASE'
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT
	,CASE
		WHEN COUNT(*) > 0
			THEN 0
		ELSE 1
		END
	,'NO RECORDS UPSERTED. (TABLE DW_IMDB_BASE_TITLE_BASICS).'
	,CASE
		WHEN SUM(ROW_COUNT) = SUM(DISTINCT_PK_COUNT)
			THEN 0
		ELSE 1
		END
	,'DATA SOURCE FAILED PRIMARY KEY TEST. (TABLE DW_IMDB_BASE_TITLE_BASICS).'
	,CASE
		WHEN (SELECT ROW_COUNT FROM X_IMDB_BASE_LOG	WHERE LOAD_SEQ_NUM = 20) = ROW_COUNT
			THEN 0
		ELSE 1
		END
	,CONCAT ('CHANGED RECORD COUNT INCORRECT. TABLE X_IMDB_BASE_TITLE_BASICS_CHG = '
		,(SELECT ROW_COUNT FROM X_IMDB_BASE_LOG	WHERE LOAD_SEQ_NUM = 20)
		,', TABLE DW_IMDB_BASE_TITLE_BASICS ='
		,ROW_COUNT)
FROM X_IMDB_BASE_LOG
WHERE LOAD_SEQ_NUM = 30
GROUP BY LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ROW_COUNT
	,DISTINCT_PK_COUNT;

COMMIT;
