/* CREATE AND LOAD ETRACT TABLE (EXT) */
DROP TABLE IF EXISTS EXT_IMDB_BASE_TITLE_BASICS;
	/* TABLE NAME AND COLUMNS SHOULD MATCH SOURCE */
	CREATE TABLE EXT_IMDB_BASE_TITLE_BASICS (
		TCONST TEXT,
		TITLETYPE INT,
		PRIMARYTITLE TEXT,
		ORIGINALTITLE TEXT,
		ISADULT INT,
		STARTYEAR INT,
		ENDYEAR INT,
		RUNTIMEMINUTES INT,
		GENRES TEXT
		);

/* CASE OF FOLLOWING LOAD SEQUENCE MUST REMAIN */
\COPY EXT_IMDB_BASE_TITLE_AKAS FROM PROGRAM 'curl "https://datasets.imdbws.com/title.basics.tsv.gz" | gunzip' QUOTE '|' DELIMITER E '\t' NULL '\N' CSV HEADER;

ANALYZE EXT_IMDB_BASE_TITLE_AKAS;

COMMIT;
