/* CREATE AND LOAD ETRACT TABLE (EXT) */
DROP TABLE IF EXISTS EXT_IMDB_BASE_TITLE_AKAS;

/* TABLE NAME AND COLUMNS SHOULD MATCH SOURCE */
CREATE TABLE EXT_IMDB_BASE_TITLE_AKAS (
	TITLEID TEXT
	,ORDERING INT
	,TITLE TEXT
	,REGION TEXT
	,LANGUAGE TEXT
	,TYPES TEXT
	,ATTRIBUTES TEXT
	,ISORIGINALTITLE INT
	);
