/* CREATE STAGING VIEW (SV) */
DROP VIEW IF EXISTS SV_IMDB_BASE_TITLE_AKAS;

/* TRANSFORMATION OF EXTERNAL COLUMN NAMES AND REMOVAL OF NULL VALUES */
CREATE VIEW SV_IMDB_BASE_TITLE_AKAS
AS
SELECT COALESCE(TITLEID, 'N/A') AS TITLEID_NK
	,COALESCE(ORDERING, 0) AS ORDERING_NK
	,COALESCE(TITLE, 'N/A') AS TITLE
	,COALESCE(REGION, 'N/A') AS REGION
	,COALESCE(LANGUAGE, 'N/A') AS LANGUAGE
	,COALESCE(TYPES, 'N/A') AS TYPES
	,COALESCE(ATTRIBUTES, 'N/A') AS ATTRIBUTES
	,COALESCE(ISORIGINALTITLE, 0) AS ISORIGINALTITLE
	,'TITLE_AKAS' AS SRC_ID
	,CURRENT_DATE AS LOAD_DATE
	,'' AS NOTE
FROM EXT_IMDB_BASE_TITLE_AKAS;
