/* DROP EXCHANGE TABLE (X) */
DROP TABLE IF EXISTS X_IMDB_BASE_TITLE_AKAS_CHG;

/* CREATE X TABLE */
CREATE TABLE X_IMDB_BASE_TITLE_AKAS_CHG (
	TITLE_ID INTEGER NULL
	,TITLE_NK TEXT NOT NULL
	,ORDERING_NK INT NOT NULL
	,TITLE TEXT NOT NULL
	,REGION TEXT NOT NULL
	,LANGUAGE TEXT NOT NULL
	,TYPES TEXT NOT NULL
	,ATTRIBUTES TEXT NOT NULL
	,ISORIGINALTITLE INT NOT NULL
	,SRC_ID TEXT NOT NULL
	,LOAD_DATE DATE NOT NULL
	,NOTE TEXT NOT NULL
	,CHG_FLG TEXT NOT NULL
  ,CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,PRIMARY KEY (TITLE_NK,ORDERING_NK)
	);

  CREATE TRIGGER X_IMDB_BASE_TITLE_AKAS_CHG_UPDT
  BEFORE UPDATE ON X_IMDB_BASE_TITLE_AKAS_CHG
  FOR EACH ROW
  EXECUTE PROCEDURE TRIGGER_SET_TIMESTAMP();
