/* CREATE AND LOAD ETRACT TABLE (EXT) */
DROP TABLE IF EXISTS EXT_IMDB_BASE_TITLE_BASICS;

/* TABLE NAME AND COLUMNS SHOULD MATCH SOURCE */
CREATE TABLE EXT_IMDB_BASE_TITLE_BASICS (
	TCONST_NK TEXT
	,TITLETYPE TEXT
	,PRIMARYTITLE TEXT
	,ORIGINALTITLE TEXT
	,ISADULT INT
	,STARTYEAR INT
	,ENDYEAR INT
	,RUNTIMEMINUTES INT
	,GENRES TEXT
	);
