/* DROP EXISTING DATA WAREHOUSE TABLE	(DW) */
DROP TABLE IF EXISTS DW_IMDB_BASE_NAME_BASICS;

/* CREATE DW TABLE */
CREATE TABLE DW_IMDB_BASE_NAME_BASICS (
	P_TCONST_ID INTEGER NULL
	,TCONST_NK TEXT NOT NULL	--(string) - alphanumeric unique identifier of the name/person
	,PRIMARYNAME  TEXT NOT NULL	--(string)– name by which the person is most often credited
	,BIRTHYEAR  TEXT NOT NULL	--in YYYY format
	,DEATHYEAR  TEXT NOT NULL	--in YYYY format if applicable, else '\N'
	,PRIMARYPROFESSION   TEXT NOT NULL	--(array of strings)– the top-3 professions of the person
	,KNOWNFORTITLES   TEXT NOT NULL --(array of tconsts) – titles the person is known for
	,SRC_ID TEXT NOT NULL
	,LOAD_DATE DATE NOT NULL
	,LAST_UPDATE DATE NOT NULL
	,NOTE TEXT NOT NULL
  ,CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,PRIMARY KEY (P_TCONST_ID)
	);

	CREATE INDEX DW_IMDB_BASE_NAME_BASICS_INDX ON DW_IMDB_BASE_NAME_BASICS (TCONST_NK);

  CREATE TRIGGER DW_IMDB_BASE_NAME_BASICS_UPDT
  BEFORE UPDATE ON DW_IMDB_BASE_NAME_BASICS
  FOR EACH ROW
  EXECUTE PROCEDURE TRIGGER_SET_TIMESTAMP();

/* INSERT DEFAULT VALUES */
INSERT INTO DW_IMDB_BASE_NAME_BASICS(
	P_TCONST_ID
	,TCONST_NK
	,PRIMARYNAME
	,BIRTHYEAR
	,DEATHYEAR
	,PRIMARYPROFESSION
	,PRIMARYPROFESSION
	,SRC_ID
	,LOAD_DATE
	,LAST_UPDATE
	,NOTE
	)
VALUES (
	0 /* AS P_TCONST_ID */
	,'N/A' /* AS TCONST_NK*/
	,'N/A' /* AS PRIMARYNAME */
	,'N/A' /* AS BIRTHYEAR */
	,'N/A' /* AS DEATHYEAR */
	,'N/A' /* AS PRIMARYPROFESSION */
	,'N/A' /* AS PRIMARYPROFESSION */
	,'NAME_BASICS' /* AS SRC_ID */
	,'19000101' /* AS LOAD_DATE */
	,'19000101' /* AS LAST_UPDATE */
	,'N/A' /* AS NOTE */
	);

	COMMIT;
