/* CREATE STAGING VIEW (SV) */
DROP VIEW IF EXISTS SV_IMDB_BASE_NAME_BASICS;

/* TRANSFORMATION OF EXTERNAL COLUMN NAMES AND REMOVAL OF NULL VALUES */
CREATE VIEW SV_IMDB_BASE_NAME_BASICS
AS
SELECT COALESCE(TCONST, 'N/A') AS TCONST_NK
	,COALESCE(PRIMARYNAME, 'N/A') AS PRIMARYNAME
	,COALESCE(BIRTHYEAR, 'N/A') AS BIRTHYEAR
	,COALESCE(DEATHYEAR, 'N/A') AS DEATHYEAR
	,COALESCE(PRIMARYPROFESSION, 'N/A') AS PRIMARYPROFESSION
	,COALESCE(KNOWNFORTITLES, 'N/A') AS KNOWNFORTITLES
	,'NAME_BASICS' AS SRC_ID
	,CURRENT_DATE AS LOAD_DATE
	,'' AS NOTE
FROM EXT_IMDB_BASE_NAME_BASICS;
