/* CREATE AND LOAD ETRACT TABLE (EXT) */
DROP TABLE IF EXISTS EXT_IMDB_BASE_TITLE_RATINGS;

	/* TABLE NAME AND COLUMNS SHOULD MATCH SOURCE */
	CREATE UNLOGGED TABLE EXT_IMDB_BASE_TITLE_RATINGS (
		TCONST TEXT
		,AVERAGERATING FLOAT
		,NUMVOTES INT
		);
