/* DROP STAGING TABLE (ST) */
DROP TABLE IF EXISTS ST_IMDB_BASE_TITLE_RATINGS;

/* CREATE ST TABLE */
CREATE TABLE ST_IMDB_BASE_TITLE_RATINGS (
	TCONST_NK TEXT NOT NULL -- ALPHANUMERIC IDENTIFIER OF RATINGS
	,AVERAGERATING FLOAT NOT NULL -- WEIGHTED AVERAGE OF ALL THE INDIVIDUAL USER RATINGS
	,NUMVOTES INT NOT NULL -- NUMBER OF VOTES THE TITLE HAS RECEIVED
	,SRC_NAME TEXT NOT NULL
	,LOAD_DATE DATE NOT NULL
	,NOTE TEXT NOT NULL
	,CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,PRIMARY KEY (
		TCONST_NK
		)
	);
