/* CREATE STAGING VIEW (SV) */
DROP VIEW IF EXISTS SV_IMDB_BASE_TITLE_RATINGS;

/* TRANSFORMATION OF EXTERNAL COLUMN NAMES AND REMOVAL OF NULL VALUES */
CREATE VIEW SV_IMDB_BASE_TITLE_RATINGS
AS
SELECT COALESCE(TCONST, 'N/A') AS TCONST_NK
	,COALESCE(AVERAGERATING, 0.0) AS AVERAGERATING
	,COALESCE(NUMVOTES, 0) AS NUMVOTES
	,'TITLE_RATINGS' AS SRC_ID
	,CURRENT_DATE AS LOAD_DATE
	,'' AS NOTE
FROM EXT_IMDB_BASE_TITLE_RATINGS;
