/* CREATE AND LOAD ETRACT TABLE (EXT) */
DROP TABLE IF EXISTS EXT_IMDB_BASE_TITLE_CREW;

/* TABLE NAME AND COLUMNS SHOULD MATCH SOURCE */
CREATE UNLOGGED TABLE EXT_IMDB_BASE_TITLE_CREW (
	TCONST TEXT
	,DIRECTORS TEXT
	,WRITERS TEXT
	);
