/* DROP STAGING TABLE (ST) */
DROP TABLE IF EXISTS ST_IMDB_BASE_TITLE_CREW;

/* CREATE ST TABLE */
CREATE TABLE ST_IMDB_BASE_TITLE_CREW (
	TCONST_NK TEXT NOT NULL -- ALPHANUMERIC UNIQUE IDENTIFIER OF THE TITLE
	,DIRECTORS TEXT NOT NULL -- DIRECTOR(S) OF THE GIVEN TITLE
	,WRITERS TEXT NOT NULL -- WRITER(S) OF THE GIVEN TITLE
	,SRC_ID TEXT NOT NULL
	,LOAD_DATE DATE NOT NULL
	,NOTE TEXT NOT NULL
	,CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
	-- ,UPDATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
  ,PRIMARY KEY (
		TCONST_NK
		)
	);

	-- CREATE TRIGGER ST_IMDB_BASE_TITLE_CREW_UPDT
	-- BEFORE UPDATE ON ST_IMDB_BASE_TITLE_CREW
	-- FOR EACH ROW
	-- EXECUTE PROCEDURE TRIGGER_SET_TIMESTAMP();
