/* CREATE STAGING VIEW (SV) */
DROP VIEW IF EXISTS SV_IMDB_BASE_TITLE_CREW;

/* TRANSFORMATION OF EXTERNAL COLUMN NAMES AND REMOVAL OF NULL VALUES */
CREATE VIEW SV_IMDB_BASE_TITLE_CREW
AS
SELECT COALESCE(TCONST, 'N/A') AS TCONST_NK
	,COALESCE(DIRECTORS, 'N/A') AS DIRECTORS
	,COALESCE(WRITERS, 'N/A') AS WRITERS
	,'TITLE_CREW' AS SRC_NAME
	,CURRENT_DATE AS LOAD_DATE
	,'' AS NOTE
FROM EXT_IMDB_BASE_TITLE_CREW;
