/* DROP EXCHANGE TABLE (X) */
DROP TABLE IF EXISTS X_IMDB_BASE_TITLE_CREW_CHG;

	/* CREATE X TABLE */
	CREATE TABLE X_IMDB_BASE_TITLE_CREW_CHG (
		P_TCONST_ID INTEGER NULL
		,TCONST_NK TEXT NOT NULL
		,DIRECTORS TEXT NOT NULL
		,WRITERS TEXT NOT NULL
		,SRC_ID TEXT NOT NULL
		,LOAD_DATE DATE NOT NULL
		,NOTE TEXT NOT NULL
		,CHG_FLG TEXT NOT NULL
		,CREATED_AT TIMESTAMPTZ NOT NULL DEFAULT NOW()
		,PRIMARY KEY (TCONST_NK)
		);
