TRUNCATE TABLE X_IMDB_BASE_TITLE_CREW_CHG;

/* DETECT CHANGES */
INSERT INTO X_IMDB_BASE_TITLE_CREW_CHG (
	TCONST_ID
	,TCONST_NK
	,PARENTTCONST
	,SEASONNUMBER
	,EPISODENUMBER
	,SRC_ID
	,LOAD_DATE
	,NOTE
	,CHG_FLG
	)
SELECT T.TCONST_ID
	,S.PARENTTCONST
	,S.SEASONNUMBER
	,S.EPISODENUMBER
	,S.SRC_ID
	,S.LOAD_DATE
	,S.NOTE
	,CASE
		WHEN T.TCONST_ID IS NULL
			THEN 'I'
		ELSE 'X'
		END
FROM ST_IMDB_BASE_TITLE_CREW S
LEFT OUTER JOIN DW_IMDB_BASE_TITLE_CREW T
	ON T.TCONST_NK = S.TCONST_NK
WHERE T.TCONST_ID IS NULL
	OR T.PARENTTCONST <> S.PARENTTCONST
	OR T.SEASONNUMBER <> S.SEASONNUMBER
	OR T.EPISODENUMBER <> S.EPISODENUMBER
	OR T.SRC_ID <> S.SRC_ID
	OR T.NOTE <> S.NOTE;

ANALYZE X_IMDB_BASE_TITLE_CREW_CHG;

/* INSERT CHANGES */
INSERT INTO DW_IMDB_BASE_TITLE_CREW (
	TCONST_ID
	,TCONST_NK
	,PARENTTCONST
	,SEASONNUMBER
	,EPISODENUMBER
	,SRC_ID
	,LOAD_DATE
	,LAST_UPDATE
	,NOTE
	)
SELECT M.MAX_ID + ROW_NUMBER() OVER (
		ORDER BY S.TCONST_NK
		)
	,S.TCONST_NK
	,S.PARENTTCONST
	,S.SEASONNUMBER
	,S.EPISODENUMBER
	,S.SRC_ID
	,S.LOAD_DATE
	,S.LOAD_DATE
	,S.NOTE
FROM X_IMDB_BASE_TITLE_CREW_CHG S
	,(
		SELECT MAX(TCONST_ID) MAX_ID
		FROM DW_IMDB_BASE_TITLE_CREW
		) M
WHERE S.CHG_FLG = 'I';

/* UPDATE CHANGES */
UPDATE DW_IMDB_BASE_TITLE_CREW
SET TCONST_NK = S.TCONST_NK
	,PARENTTCONST = S.PARENTTCONST
	,SEASONNUMBER = S.SEASONNUMBER
	,EPISODENUMBER = S.EPISODENUMBER
	,SRC_ID = S.SRC_ID
	,LAST_UPDATE = S.LOAD_DATE
	,NOTE = S.NOTE
FROM X_IMDB_BASE_TITLE_CREW_CHG S
WHERE S.TCONST_NK = DW_IMDB_BASE_TITLE_CREW.TCONST_NK
	AND S.CHG_FLG = 'X';

ANALYZE DW_IMDB_BASE_TITLE_CREW;

/* SAVE LOAD LOG HISTORY */
INSERT INTO X_IMDB_BASE_LOG (
	LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT
	)
SELECT NOW()
	,30
	,S.SRC_ID
	,'DW_IMDB_BASE_TITLE_CREW'
	,S.LOAD_DATE AS LOAD_DATE
	,T.ST_ROW_COUNT AS ST_ROW_COUNT
	,COUNT(S.*) AS DW_ROW_COUNT
	,NULL AS DISTINCT_COUNT
FROM DW_IMDB_BASE_TITLE_CREW S
JOIN X_IMDB_BASE_LOG T
	ON S.SRC_ID = T.SRC_ID
    AND S.LOAD_DATE = T.LOAD_DATE
WHERE T.LOAD_SEQ_NUM = 10
	AND T.OBJECT_NAME = 'ST_IMDB_BASE_TITLE_CREW'
	AND T.LOAD_DATE = (
		SELECT MAX(LOAD_DATE)
		FROM ST_IMDB_BASE_TITLE_CREW
		)
GROUP BY S.SRC_ID
	,S.LOAD_DATE
	,T.ST_ROW_COUNT;

/* SAVE ETL LOG HISTORY */
INSERT INTO ETL_LOG (
	SUBJECT_AREA
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT
	,FAIL_CHECK_BOOL_1
	,ERROR_MESSAGE_1
	,FAIL_CHECK_BOOL_2
	,ERROR_MESSAGE_2
	,FAIL_CHECK_BOOL_3
	,ERROR_MESSAGE_3
	)
SELECT 'IMDB_BASE'
	,LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_IDS
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT
	,CASE
		WHEN SUM(ST_ROW_COUNT) = SUM(DW_ROW_COUNT)
			THEN 0
		ELSE 1
		END
	,CONCAT (
		'ROW COUNTS FOR THE LATEST LATEST TRANSACTION DATE DO NOT MATCH SOURCE. SOURCE ST (ST_IMDB_BASE_TITLE_CREW) = '
		,ST_ROW_COUNT
		,' DW (DW_IMDB_BASE_TITLE_CREW) = '
		,DW_ROW_COUNT
		,'.'
		)
	,0
	,'N/A'
	,0
	,'N/A'
FROM X_IMDB_BASE_LOG
WHERE LOAD_SEQ_NUM = 30
GROUP BY LOAD_TIMESTAMP
	,LOAD_SEQ_NUM
	,SRC_ID
	,OBJECT_NAME
	,LOAD_DATE
	,ST_ROW_COUNT
	,DW_ROW_COUNT
	,DISTINCT_COUNT;

COMMIT;
