/* CREATE STAGING VIEW (SV) */
DROP VIEW IF EXISTS SV_IMDB_BASE_TITLE_EPISODE;

/* TRANSFORMATION OF EXTERNAL COLUMN NAMES AND REMOVAL OF NULL VALUES */
CREATE VIEW SV_IMDB_BASE_TITLE_EPISODE
AS
SELECT COALESCE(TCONST, 'N/A') AS TCONST_NK
	,COALESCE(PARENTTCONST, 'N/A') AS PARENTTCONST
	,COALESCE(SEASONNUMBER, 0) AS SEASONNUMBER
	,COALESCE(EPISODENUMBER, 0) AS EPISODENUMBER
	,'TITLE_EPISODE' AS SRC_NAME
	,CURRENT_DATE AS LOAD_DATE
	,'' AS NOTE
FROM EXT_IMDB_BASE_TITLE_EPISODE;
