/* COPY EXTERNAL DATA INTO EXT TABLE */
TRUNCATE TABLE EXT_IMDB_BASE_NAME_BASICS;

/* CHARACTER CASE OF THE FOLLOWING LOAD SEQUENCE MUST REMAIN */
COPY EXT_IMDB_BASE_NAME_BASICS FROM PROGRAM 'curl "https://datasets.imdbws.com/names.basics.tsv.gz" | gunzip' QUOTE '|' DELIMITER E'\t' NULL '\N' CSV HEADER;

ANALYZE EXT_IMDB_BASE_NAME_BASICS;

COMMIT;
