TRUNCATE TABLE EXT_IMDB_BASE_TITLE_AKAS;

/* CHARACTER CASE OF THE FOLLOWING LOAD SEQUENCE MUST REMAIN */
COPY EXT_IMDB_BASE_TITLE_AKAS FROM PROGRAM 'curl "https://datasets.imdbws.com/title.akas.tsv.gz" | gunzip' QUOTE '|' DELIMITER E'\t' NULL '\N' CSV HEADER;

ANALYZE EXT_IMDB_BASE_TITLE_AKAS;

COMMIT;
